### ISSUE TITLE
i think some cmdid.

### ISSUE THREAD

**Issue by wkavenger** [NickTheHuy/3.4_proto#1]
GetAllMailReq:1416
GetAllMailRsp:1413

same name in 2.8、3.3
3.4 sniffer it's two cmdid.

**Comment by Hiro420** [comment]
GetAllMailReq is 1424 and GetAllMailRsp is 1429
in 3.3 the Req was 1427 and the Rsp was 1439

**Comment by wkavenger** [comment]
your are right,my fault.
